# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor_Unavailability',
            new_name='ProfessorUnavailability',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='start_time',
        ),
        migrations.AddField(
            model_name='offering',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
